services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: suite_development
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.1

  web:
    environment:
      REDIS_URL: redis://redis:6379/1
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379/1

volumes:
  db_data:
