# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: development
  password: development

development:
  <<: *default
  database: suite_development
  username: development
  password: development

test:
  <<: *default
  database: suite_test
  username: development
  password: development

production:
  <<: *default
  database: suite_production